### ISSUE TITLE
Implement inline arguments

### ISSUE THREAD

**Issue by iamutaki** [spotwilliams/validator#2]
How do you implement multiple rules with inline parameters like 'min:1' or 'max:100', just in case if i want to create create validation like 'contains:we are, somos, kami',

**Comment by spotwilliams** [comment]
I don't know I would go on that direction, would be beneficial when using it? Besides that will look more like Laravel, what other benefit can we find on implement that?

**Comment by iamutaki** [comment]
in my opinion, the advantage is the ease of use, as like will only need one command line to perform the validation, but it's true that it will look a like Laravel validation.Just want to ask, do you have plans to implement something like that in the future?

**Comment by spotwilliams** [comment]
Not right now, prefer the simplicity of the implementation. thanks for ask
